### ISSUE TITLE
valid XHTML

### ISSUE THREAD

**Issue by cdrubin** [trevnorris/jqml#1]
Hey there Trevor

Thanks for a fun library, just thinking of ways to integrate with Agility.JS at the moment. What I wonder though is how you suggest I get this kind of HTML element to be generated : 
<code>&lt;br /&gt;</code>

Doing this :
<code>[ 'br' ]</code> results in <code>&lt;br&gt;</code>
which isn't good-neighbourly XHTML

What do you suggest? Thanks!

 -Daniel

**Comment by trevnorris** [comment]
@cdrubin, jqml actually doesn't generate a string that gets injected into the page via `innerHTML`. Instead it uses the DOM specification to generate Elements on the fly. So when you see `<br>`, that's actually just how your browser is interpreting the `<br>` DOM element.

If you let me know more of how you plan on using it, be more than happy to help out.

**Comment by cdrubin** [comment]
Thanks for the speedy response Trevor and great point! The non-issue I mentioned probably says more about Firebug and Firefox then! I went looking for a JSON -> HTML format because of what I think is the ugliness of multi-line strings that are used a few lines into this section : http://agilityjs.com/docs/docs.html#bindings 

Again, thanks for the plug-in and help. Methinks this might become my way of avoiding raw HTML in the view definitions. It is a shame the same cannot be as easily done for CSS but this is a start! :)

-Daniel

**Comment by trevnorris** [comment]
@cdrubin not a problem. That's actually why I've prefered JsonML over other standard template languages. Usually parts of a template require a fair bit of logic, and I've found it a lot easier to step through creation when each part of the template is it's own javascript object.
